# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FOUR A<sup><sub>'S</sub></sup> FIVE H<sup><sub>'S</sub></sup>
subtitle: books on design, new &amp; used
email: hello@aaaahhhhh.com
description: > # this means to ignore newlines until "baseurl:"
  Four A's Five H's is an online shop for books and periodicals on graphic design and architecture
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaaahhhhh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FourAsFiveHs
instagram_username:  FourAsFiveHs
author: Matthew howe
Snipcart_API: MGU4ZGQ1YjItZWU3Ni00OTkwLWE0NzMtMmZhYWVjZjIxODc5NjM2MjgzOTM4OTY3MjkwNjE3
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
    sass_dir: _sass

    sass:
    style: compressed

collections:
      products:
        output: true
        permalink: /product/:path/


defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      

