# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
###############################################################
## Site Variables
###############################################################
title: Four A's Five H's
subtitle: Books on Art, Design, Architecture, et al.
email: hello@aaaahhhhh.com
description: Books on Art, Design, Architecture, et al.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aaaahhhhh.com" # the base hostname & protocol for your site, e.g. http://example.com
###############################################################
## Social Media Variables
###############################################################
twitter_username: discoform
github_username: discoform
linkedIn_username: matthew-h-49303a139/
instagram_username: discoform
###############################################################
## Author Variables
###############################################################
author: discoform
authorURL: https://discoform.com
headerImage:
###############################################################
## Snipcart 
###############################################################
Snipcart_API: YOUR_API
###############################################################
## Build settings
###############################################################
markdown: kramdown
###############################################################
## Plugins etc
###############################################################
plugins:
# compress_images:
  # images_path: "/assets/images/product-images/**/*.{gif,png,jpg,jpeg,svg}"
exclude:
  - Gemfile
  - Gemfile.lock
###############################################################
## Sass Settings
###############################################################
sass:
    sass_dir: _scss
    sass:
    style: compressed
###############################################################
## Collections
###############################################################
collections:
      products:
        output: true
        permalink: /product/:path/
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"