backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/assets/images/product-images" # Media files will be stored in the repo under images/uploads


collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "product" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "products"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subTitle", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publisher", name: "publisher", widget: "string"}
      - {label: "Publication Date", name: "publicationDate", widget: "number"}
      - {label: "Condition", name: "condition", widget: "string"}
      - {label: "Binding", name: "binding", widget: "string"}
      - {label: "ISBN", name: "ISBN", widget: "number"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Weight", name: "weight", widget: "number", default: "250"}
      - {label: "Quantity", name: "quantity", widget: "string"}
      - {label: "Description", name: "summary", widget: "markdown"}
      - {label: "Vimeo ID", name: "vimeo", widget: "string"}
      - {label: "Vimeo Caption", name: "videoCaption", widget: "string"}
      - {label: "Publish?", name: "published", widget: "string", default: "true"}
